# Generated by Django 4.2 on 2023-04-22 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0003_user_dark_mode'),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='confirmed',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='moderator.moderator'),
        ),
    ]
