# Generated by Django 4.2 on 2023-04-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0002_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
