# Generated by Django 4.2 on 2023-04-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0003_user_dark_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderator',
            name='is_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moderator',
            name='role',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
