# Generated by Django 4.2 on 2023-05-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0005_logins'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderator',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
